#!/usr/bin/perl -w
#
# Dumps all files specified in the command-line into one file. Useful for
# concatenating the files generated by adaf_family_manyfiles.pl and then
# plotting all the solutions together.

# Filename of file which will contain all output files
$all="outputs.dat";

# Error handling
$args=@ARGV;
if ($args == 0) {
  print "Usage: group_files.pl FILES \n";
  exit;
}

# Sorts the filenames
my @ARGV = sort alternateSort @ARGV;

open (OUTFILE, ">$all");

foreach $file (@ARGV) {
  open (INFILE, $file);
  while (<INFILE>) {
    print OUTFILE $_;
  }
  close(INFILE);
  print OUTFILE "\n\n";
}

close(OUTFILE);

print "File $all created! \n";


# Sorting procedure for sorting the filenames with the structure basename-####.dat,
# where the length of the number in the filename is arbitrary. The method 
# consists of considering only the number in the filename and use it to do 
# the sorting.
sub alternateSort {
  $tmp1=length $a; # calculates the length of the strings (filenames)
  $tmp2=length $b;
# Extracts the number part of the filenames and compares only the numbers
  substr($a, 7, $tmp1-4-7) cmp substr($b, 7, $tmp2-4-7)
}
